from enum import Enum

class Resp_CodigoRespuesta(Enum):
    NONE = 0
    ERROR_FUNCIONAL = 1
    ERROR_INTEGRACION = 2
    ERROR_CONFIGURACION = 3
    ERROR_HAY_FACTURA_PENDIENTE = 9

class Operacion(Enum):
    VENTA = "VTA"
    DEVOLUCION = "DEV"

class MonedaISO(Enum):
    PESOS = "0858"
    DOLARES = "0840"

class Resp_EstadoAvance(Enum):
    ESTADOAVANCE_SINDEFINIR = 0
    ESTADOAVANCE_PENDIENTE_PROCESO = 1
    ESTADOAVANCE_ENPROCESO = 2
    ESTADOAVANCE_PROCESADA_SIN_CONFIRMAR = 3
    ESTADOAVANCE_FINALIZADA_CORRECTAMENTE = 4
    ESTADOAVANCE_FINALIZADA_ERROR = 5
    ESTADOAVANCE_CANCELADA = 6


class TarjetaId(Enum):
    TODAS = 0
    MASTERCARD = 1
    VISA = 2
    DINERS = 3
    AMERICAN_EXPRESS = 4
    TARJETA_D = 5
    OCA = 6
    CABAL = 8
    ANDA = 9
    CREDITEL = 12
    PASSCARD = 14
    LIDER = 15
    CLUB_DEL_ESTE = 16
    MAESTRO = 17
    EDENRED_ALIMENTACION = 19
    SODEXO_ALIMENTACION = 20
    MI_DINERO_ALIMENTACION = 21
    MIDES = 22

class EmisorId(Enum):
    TODOS = 0
    HSBC = 11
    BROU = 1
    ITAU = 12
    BANDES = 7
    CITIBANK = 9
    SCOTIABANK = 8
    OCA = 14
    SANTANDER = 13
    FUCAC = 15
    BBVA = 10
    SANTANDER_MOLINETES = 1301
    PRONTO = 22
    SANTANDER_SELECT = 1302




